import Head from "next/head";

import { Page, AboutMe } from "../components/blocks";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/leaf-svgrepo-com.svg" />
      </Head>
      <Page hasNav backgroundColor={"primary"}>
        <AboutMe />
      </Page>
      <Page backgroundColor={"gradient"}><div /></Page>
      <Page backgroundColor={"primary"}><div /></Page>
    </div>
  );
}
