import Head from "next/head";
import Image from "next/image";

import Panel from "../components/Panel";
import AboutMe from "../components/AboutMe";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/leaf-svgrepo-com.svg" />
      </Head>
      <Panel hasNav backgroundColor={"primary"}>
        <AboutMe />
      </Panel>
      <Panel backgroundColor={"gradient"} />
      <Panel backgroundColor={"primary"} />
    </div>
  );
}
